const {chromium}=require('C:/Users/USER/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs');
const assert=require('node:assert/strict');
(async()=>{
  const browser=await chromium.launch({headless:true,channel:'chrome',args:['--enable-unsafe-swiftshader']});
  const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1});
  const page=await context.newPage();const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('Failed to load resource'))errors.push(m.text());});
  page.on('requestfailed',request=>{if(request.url().startsWith('http://127.0.0.1:8125/')&&!request.url().includes('/api/'))errors.push(request.url()+': '+request.failure()?.errorText);});
  await page.goto('http://127.0.0.1:8125');await page.waitForLoadState('networkidle');
  await page.evaluate(async()=>{
    const trips=await import('./js/trips.js');const app=await import('./js/app.js');
    const maps=await import('./js/maps/store.js');const packages=await import('./js/maps/packages.js');
    const trip=await trips.createTrip({name:'בדיקת תאילנד',startDate:'2026-11-01',endDate:'2026-11-10',currency:'THB'});
    await maps.savePlace({tripId:trip.id,title:'מלון בבנגקוק',type:'lodging',lat:13.7563,lng:100.5018,date:'2026-11-01',order:1,notes:'כניסה אחרי 15:00'});
    await maps.savePlace({tripId:trip.id,title:'ארמון המלך',type:'attraction',lat:13.7500,lng:100.4913,date:'2026-11-01',order:2});
    const catalog=await packages.catalog();await packages.downloadPackage(catalog.find(p=>p.id==='bangkok'));
    app.setActiveTrip(trip.id);app.navigate('map');
    await navigator.serviceWorker.ready;
  });
  await page.waitForSelector('.maplibregl-canvas');await page.waitForTimeout(3500);
  fs.mkdirSync('scratch/screenshots',{recursive:true});
  await page.screenshot({path:'scratch/screenshots/map-phone.png',fullPage:true});
  console.log('markers:',await page.locator('.map-pin').count());
  await page.getByRole('button',{name:'הורדת מפות',exact:true}).click();
  await page.waitForSelector('.map-country-heading');
  const countries=await page.locator('.map-country-heading .grow').allTextContents();
  assert.deepEqual(countries,['גאורגיה','ישראל','תאילנד']);
  await page.getByRole('searchbox',{name:'חיפוש מדינה'}).fill('תאילנד');
  assert.equal(await page.locator('.map-country:visible').count(),1);
  await page.locator('.map-country:visible summary').click();
  assert.equal(await page.locator('.map-country:visible .map-download-row:visible').count(),6);
  await page.getByRole('button',{name:'סגור',exact:true}).click();
  const dates=await page.locator('.map-place-date').first().evaluate(node=>({size:getComputedStyle(node).fontSize,parent:getComputedStyle(node.parentElement).fontSize,align:getComputedStyle(node).textAlign}));
  assert.equal(parseFloat(dates.size)/parseFloat(dates.parent),0.7);assert.equal(dates.align,'right');
  for(const type of ['satellite','hybrid','terrain']){
    const tile=page.waitForResponse(r=>r.url().startsWith('https://tiles.maps.eox.at/')&&r.status()===200,{timeout:30000});
    await page.getByRole('combobox',{name:'סוג מפה',exact:true}).selectOption(type);
    await tile;await page.waitForTimeout(1000);
    assert.equal(await page.locator('.map-pin').count(),2);
    assert.match(await page.locator('.map-coverage').textContent(),/אונליין/);
    await page.screenshot({path:`scratch/screenshots/map-${type}.png`});
  }
  console.log('country search, date size and satellite/hybrid/terrain: passed');
  await page.getByRole('button',{name:'פתח מפה במסך מלא',exact:true}).click();
  await page.waitForTimeout(400);await page.screenshot({path:'scratch/screenshots/map-fullscreen.png'});
  await page.getByRole('button',{name:'צא ממסך מלא',exact:true}).click();
  await context.setOffline(true);
  await page.waitForFunction(()=>document.querySelector('[aria-label="סוג מפה"]')?.value==='streets');
  await page.waitForFunction(()=>document.querySelectorAll('.map-pin').length===2);
  assert.equal(await page.locator('.map-pin').count(),2);
  await page.reload();await page.waitForSelector('#nav button');
  await page.getByRole('button',{name:'מפה',exact:true}).click();await page.waitForSelector('.maplibregl-canvas');await page.waitForTimeout(2500);
  await page.screenshot({path:'scratch/screenshots/map-offline.png'});
  console.log('offline markers:',await page.locator('.map-pin').count());
  await page.getByRole('button',{name:'מלון בבנגקוק',exact:true}).click();
  console.log('offline note:',await page.locator('textarea').inputValue());
  console.log('errors:',JSON.stringify(errors));
  await browser.close();if(errors.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;});
